services:
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop-m
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "23306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:7.4.0
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis:/data/
  redis-insight:
    image: redis/redisinsight:2.64.1
    restart: unless-stopped
    ports:
      - "15540:5540"
    volumes:
      - ./data/redis-insight:/data