
spring:
  application:
    name: shop-m
  messages:
    basename: messages,errors
    encoding: UTF-8
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:23306/shop
      username: dev_user
      password: dev_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: ShopConnectionPool
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 16379
      repositories:
        enabled: false
#  session:
#    redis:
#      namespace: "shop_m:user_session"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
    com.fasterxml.jackson: DEBUG
#    org.springframework: DEBUG
#    com.zaxxer.hikari: debug