
spring:
  application:
    name: shop-product
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:23306/shop
      username: dev_user
      password: dev_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: ShopConnectionPool
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        delivery.timeout.ms: 10000
        request.timeout.ms: 3000
        retry.backoff.ms: 100
        partitioner:
          class: org.apache.kafka.clients.producer.RoundRobinPartitioner
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: latest
      properties:
        allow.auto.create.topics: false
        enable.auto.commit: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
shop:
  kafka:
    topics:
      product-created:
        topic: product-created
        group-id: product-created-group
        concurrency: 1