
spring:
  application:
    name: shop-product
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:23306/shop
      username: dev_user
      password: dev_password
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: ShopConnectionPool
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

shop:
  kafka:
    topics:
      product-created:
        topic: product-created
        group-id: product-created-group
        concurrency: 1